export { default as Splash } from './Splash';
export { default as Home } from './Home';
export { default as Login } from './LoginSetup/LoginSetup';
export { default as ForgotPassword } from './ForgotPassword';
export { default as Dashboard } from './Dashboard';
export { ProfileSetup } from './ProfileSetup';
export { Profile } from './Profile';
export { default as NotFound } from './NotFound';
export { default as TermsOfService } from './TermsOfService';
export { default as PrivacyPolicy } from './PrivacyPolicy';
